apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-app
  template:
    metadata:
      labels:
        app: log-output-app
    spec:
      containers:
        - name: log-output-app
          image: erjav/log-output-app@sha256:1fab007477e5dd61cbf94331bfa6ad1e1ca5ce47e313de4659be41ab3fa2fe98
          imagePullPolicy: IfNotPresent
