apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logs
  template:
    metadata:
      labels:
        app: logs
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: logs-claim
      containers:
        - name: log-outputter
          image: erjav/log-outputter@sha256:1ee4d05d11a317dd802931d89dfdc326cb5fd95ec9f1ccd7a022d0b2967e8159
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
        - name: log-reader
          image: erjav/log-reader@sha256:ffe3c5ceeede117b7da337b2ba6a1c4e4d89ad4697e4b4849c56748abb8ba283
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
