apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logs
  template:
    metadata:
      labels:
        app: logs
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
      containers:
        - name: log-outputter
          image: erjav/log-outputter@sha256:1ee4d05d11a317dd802931d89dfdc326cb5fd95ec9f1ccd7a022d0b2967e8159
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
        - name: log-reader
          image: erjav/log-reader@sha256:ed2fe9ff664b1f1f5acfcfd443f41b8991333442092e126bf37b428c6c611668
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
