apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
      - name: pingpong
        image: erjav/pingpong@sha256:8a185102af73e53c25df14455586203978141175250af43b6a2e6c04941c3543
        imagePullPolicy: IfNotPresent
        securityContext:
            runAsUser: 0
        volumeMounts:
        - name: shared-logs
          mountPath: /usr/src/app/files
      volumes:
      - name: shared-logs
        persistentVolumeClaim:
          claimName: logs-claim
